apps/admin_side/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path('login/',views.login, name='user_login'),
    path('logout/',views.logout_view, name='logout'),
    
    #player
    path("player_list_/", views.player_list_, name="player_list_"),
    path("create_player_/", views.create_player_, name="create_player_"),
    path("player_view_/<int:user_id>/", views.player_view, name="player_view"),
    path("edit_player_/<int:user_id>/", views.edit_player, name="edit_player"),
    path("delete_player_/<int:user_id>/", views.delete_player, name="delete_player"),
    
    #merchant request
    path("merchant_request_list/", views.merchant_request_list, name="merchant_request_list"),

    # team
    path("team_list_for_admin/", views.team_list_for_admin, name="team_list_for_admin"),
    path("create_team_/", views.create_team_, name="create_team_"),
    path("edit_team_/<int:team_id>", views.edit_team_, name="edit_team_"),
    path("delete_team_/<int:team_id>", views.delete_team_, name="delete_team_"),
    path("view_team_/<int:team_id>", views.view_team_, name="view_team_"),  
    
    #user not use
    path('create_user_/', views.create_user, name="create_user"),
    path('user_list_/<str:filter_by>', views.user_list, name="user_list"),
    path('view_user_/<int:user_id>/', views.view_user, name="view_user"),
    path('edit_user_/<int:user_id>/', views.edit_user, name="edit_user"),
    path('delete_user_/<int:user_id>/', views.delete_user, name="delete_user"),

    path("tournamnet_list/<str:filter_by>", views.tournament_list, name="tournamnet_list"),
    path("view_tournament/<int:tour_id>/", views.view_tournament, name="view_tournament"),
    path("hit_start_tournamnet/<int:tour_id>/", views.hit_start_tournamnet, name="hit_start_tournamnet"),
    path("create_tournamnet/", views.create_tournamnet, name="create_tournamnet"),
    # path("edit_tournamnet/<int:tour_id>/", views.edit_tournamnet, name="edit_tournamnet"),
    path("update_match/<int:set_score_id>/", views.update_match, name="update_match"),
    path("edit_tournament/<int:tour_id>/", views.edit_tournament, name="edit_tournament"),
    path("edit_matches__score/<int:tour_id>/", views.edit_matches__, name="edit_matches__score"),
    path('update-match-order/', views.update_match_order, name='update_match_order'),
    path("submit_score/<int:tour_id>/", views.submit_score, name="submit_score"),
    path("delete_tournament/<int:tour_id>/", views.delete_tournament, name="delete_tournament"),


    path("advertisement_list_/", views.advertisement_list, name="advertisement_list"),
    path("advertisement_view_/<int:ad_id>/", views.advertisement_view, name="advertisement_view"),
    path("advertisement_approve_/<int:ad_id>/", views.ad_approve, name="advertisement_approve"),
    path("advertisement_reject_/<int:ad_id>/", views.ad_reject, name="advertisement_reject"),
    path("ambassador_post_list_/", views.ambassador_post_list, name="ambassador_post_list"),
    path("ambassador_post_approve_/<int:post_id>/", views.ambassador_post_approve, name="ambassador_post_approve"),
    path("ambassador_post_reject_/<int:post_id>/", views.ambassador_post_reject, name="ambassador_post_reject"),
    
    path("admin_profile/", views.admin_profile, name="admin_profile"),
   
    path("app_update/", views.app_update, name="app_update"),
    path("create_open_play/", views.create_open_play, name="create_open_play"),
    path("add_product/", views.add_product, name="add_product"),
    path("product_list/", views.product_list, name="product_list"),
    path("view_product/<int:product_id>/", views.view_product, name="view_product"),
    path("edit_product/<int:product_id>/", views.edit_product, name="edit_product"),
    path("delete_product/<int:product_id>/", views.delete_product, name="delete_product"),
    
    path("send_universal_notification/", views.send_universal_notification, name="send_universal_notification"),
    path("payment_table/", views.payment_table, name="payment_table"),

    path("merchant_request_list/",views.merchant_request_list, name="merchant_request_list"),
    path("version_update_list/", views.version_update_list, name="version_update_list"),
    path("update_version/", views.version_update, name="update_version"),
    
    path("read_notification/", views.mark_notifications_as_read, name="mark_notifications_as_read"),


    #socail feed
    path("social_feed_list/", views.social_feed_list, name="social_feed_list"),
    path("add_social_feed/", views.add_social_feed, name="add_social_feed"),
    path("social_feed_view/<int:post_id>/", views.social_feed_view, name="social_feed_view"),
    path("edit_social_feed/<int:post_id>/", views.edit_social_feed, name="edit_social_feed"),
    path("delete_file/<int:file_id>/", views.delete_file, name="delete_file"),

    path('club_list/', views.club_list, name="club_list")
    
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.user.views import account_deletion_request
from apps.team import views
from django.shortcuts import render
from apps.user.views import event_matches_table
from apps.user.models import User
from datetime import datetime
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def account_deletion_requestweb(request):
    context = {"message": None}
    try:
        if request.method == "POST":
        
            email = request.POST.get('email')
            reason = request.POST.get('reason', None)  # Get reason for deletion
            user_ins = User.objects.filter(email=email)
            
            if not user_ins.exists():
                context["message"] = "not find user"
                return render(request, 'email/deletion_request.html', context)
            user = user_ins.first()
            # Prepare email content
            context = {
                "full_name": f"{user.first_name} {user.last_name}",
                "user_email": email,
                "reason": reason,
                "date_now": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            }

            # Render HTML email
            html_content = render_to_string('email/delete_request.html', context)
            text_content = strip_tags(html_content)  # Plain text version

            # Send email
            subject = "Request for Account Deletion"
            from_email = email  # The user's email address
            # recipient_list = ["joinpickleit@gmail.com"]  # Admin email
            recipient_list = ["joinpickleit@gmail.com"]

            email_message = EmailMultiAlternatives(subject, text_content, from_email, recipient_list)
            email_message.attach_alternative(html_content, "text/html")
            email_message.send()

            return render(request, 'email/deletion_request.html', context)
        else:
            return render(request, 'email/deletion_request.html', context)
    except Exception as e:
        context["message"] = str(e)
        return render(request, 'email/deletion_request.html', context)

def index(req):
    return render(req, "index/index.html")

def privacy_policy(req):
    return render(req, "index/privacy-policy.html")

def terms_conditions(req):
    return render(req, "index/terms-conditions.html")

urlpatterns = [
    path('', index, name="index"),
    path('privacy_policy/', privacy_policy, name="privacy_policy"),
    path('terms_conditions/', terms_conditions, name="terms_conditions"),
    path('pickleit-admin-main/', admin.site.urls),
    path('api_list/', views.api_list,name="api_list"),
    path('user/', include('apps.user.urls')),
    path('team/', include('apps.team.urls')),
    path('accessories/', include('apps.pickleitcollection.urls')),
    path('chat/', include('apps.chat.urls')),
    path('admin/', include('apps.admin_side.urls')),
    path('accessories/', include('apps.store.urls')),
    path('court/', include('apps.courts.urls')),
    path('socialfeed/', include('apps.socialfeed.urls')),
    path('clubs/', include('apps.clubs.urls')),
    path('user_side/', include('apps.user_side.urls')),
    path('requestdeletion1/', account_deletion_request, name="account_deletion_request"),
    path('requestdeletion/', account_deletion_requestweb, name="account_deletion_requestweb"),
    path('events/matches/table/', event_matches_table, name="event_matches_table"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/admin_side/models.py
from django.db import models

# Create your models here.

apps/admin_side/templates/dashboard/side/update/app_update_list.html
<!-- Ensure you're including Bootstrap's CSS and JavaScript files -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Your template code -->
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style>
        /* Your CSS styles */
    </style>
{% endblock %}
{% block page_title %}
    App Version List
{% endblock %}
{% block content %}
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">App versions</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <div class="d-flex flex-row-reverse m-4">
                            <a href="#" class="btn btn-primary font-weight-bold" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Add Update</a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="card">            
            <div class="card-body">
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th class="h5 font-weight-bold text-center">Name</th>
                            <th class="h5 font-weight-bold text-center">version</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for da in data %}
                            <tr>
                                <td>PICKLEit</td>
                                <td>
                                    {% for vr in da %}
                                    <p>{{vr}}</p>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Version</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label  class="col-form-label">Version:</label>
                            <input type="text" class="form-control" name="version" />
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

apps/admin_side/templates/dashboard/side/update/version_update.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Your template code -->
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style>
        /* Your CSS styles */
    </style>
{% endblock %}
{% block page_title %}
    Update App Version
{% endblock %}
{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Add App Version</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                </nav>
            </div>
        </div>
    </div>
</div>
    
<div class="container-fluid row justify-content-center align-items-center">
    <div class="card col-6 p-5">
        <div class="card-body ">
            <form method="post" class="farm-fields-form">
                {% csrf_token %}              
                    
                <div class="form-group row">        
                    <label for="version">Version</label>
                    <input type="text" name="version" id="version" class="textinput textInput form-control">
                </div>
                <div class="form-group row">  
                    <label for="release_date">Release Date</label>
                    <input type="date" name="release_date" id="release_date" class="textinput textInput form-control" >
                </div>
                <div class="form-group row">  
                    <label for="description">Description</label>
                    <input type="text" name="description" id="description" class="textinput textInput form-control" >
                </div>        
                <div class="row mt-3 text-center">
                    <div class="form-btn-row">
                        <input style="display: none;" id="subbtn" type="submit" class="btn-save-submit" value="Save"> 
                        <input type="submit" class="btn-save-submit" value="Save"> 
                    </div>
                </div>       
            </form>
        </div> 
    </div>
</div>
{% endblock content %}

apps/admin_side/templates/dashboard/side/update/version_updates_list.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Your template code -->
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style>
        /* Your CSS styles */
    </style>
{% endblock %}
{% block page_title %}
    App Version List
{% endblock %}
{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">App versions</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <div class="d-flex flex-row-reverse m-4">
                        <a href="{% url 'dashboard:update_version' %}" class="btn btn-primary font-weight-bold">Add Update</a>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="card-body">
        <div class="table-responsive">
            <table id="zero_config" class="table table-striped table-bordered">
                <thead>
                    <tr style="border-bottom: 2px solid #e0e0e0;">
                        <th width="40%">Version</th>
                        <th width="10%">Release Date</th>
                        <th width="10%">Description</th>
                        <th width="10%">Created By</th>                                
                    </tr>
                </thead>
                <tbody>
                    {% for version in version_updates %}
                    <tr>
                        <td>{{version.version}}</td>
                        <td>{{version.release_date}}</td>
                        <td>{{version.description}}</td>
                        <td>{{version.created_by}}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>                                        
        </div>
    </div>
</div>   

{% endblock content %}