apps/admin_side/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path('login/',views.login, name='user_login'),
    path('logout/',views.logout_view, name='logout'),
    
    #player
    path("player_list_/", views.player_list_, name="player_list_"),
    path("create_player_/", views.create_player_, name="create_player_"),
    path("player_view_/<int:user_id>/", views.player_view, name="player_view"),
    path("edit_player_/<int:user_id>/", views.edit_player, name="edit_player"),
    path("delete_player_/<int:user_id>/", views.delete_player, name="delete_player"),
    
    #merchant request
    path("merchant_request_list/", views.merchant_request_list, name="merchant_request_list"),

    # team
    path("team_list_for_admin/", views.team_list_for_admin, name="team_list_for_admin"),
    path("create_team_/", views.create_team_, name="create_team_"),
    path("edit_team_/<int:team_id>", views.edit_team_, name="edit_team_"),
    path("delete_team_/<int:team_id>", views.delete_team_, name="delete_team_"),
    path("view_team_/<int:team_id>", views.view_team_, name="view_team_"),  
    
    #user not use
    path('create_user_/', views.create_user, name="create_user"),
    path('user_list_/<str:filter_by>', views.user_list, name="user_list"),
    path('view_user_/<int:user_id>/', views.view_user, name="view_user"),
    path('edit_user_/<int:user_id>/', views.edit_user, name="edit_user"),
    path('delete_user_/<int:user_id>/', views.delete_user, name="delete_user"),

    path("tournamnet_list/<str:filter_by>", views.tournament_list, name="tournamnet_list"),
    path("view_tournament/<int:tour_id>/", views.view_tournament, name="view_tournament"),
    path("hit_start_tournamnet/<int:tour_id>/", views.hit_start_tournamnet, name="hit_start_tournamnet"),
    path("create_tournamnet/", views.create_tournamnet, name="create_tournamnet"),
    # path("edit_tournamnet/<int:tour_id>/", views.edit_tournamnet, name="edit_tournamnet"),
    path("update_match/<int:set_score_id>/", views.update_match, name="update_match"),
    path("edit_tournament/<int:tour_id>/", views.edit_tournament, name="edit_tournament"),
    path("edit_matches__score/<int:tour_id>/", views.edit_matches__, name="edit_matches__score"),
    path('update-match-order/', views.update_match_order, name='update_match_order'),
    path("submit_score/<int:tour_id>/", views.submit_score, name="submit_score"),
    path("delete_tournament/<int:tour_id>/", views.delete_tournament, name="delete_tournament"),


    path("advertisement_list_/", views.advertisement_list, name="advertisement_list"),
    path("advertisement_view_/<int:ad_id>/", views.advertisement_view, name="advertisement_view"),
    path("advertisement_approve_/<int:ad_id>/", views.ad_approve, name="advertisement_approve"),
    path("advertisement_reject_/<int:ad_id>/", views.ad_reject, name="advertisement_reject"),
    path("ambassador_post_list_/", views.ambassador_post_list, name="ambassador_post_list"),
    path("ambassador_post_approve_/<int:post_id>/", views.ambassador_post_approve, name="ambassador_post_approve"),
    path("ambassador_post_reject_/<int:post_id>/", views.ambassador_post_reject, name="ambassador_post_reject"),
    
    path("admin_profile/", views.admin_profile, name="admin_profile"),
   
    path("app_update/", views.app_update, name="app_update"),
    path("create_open_play/", views.create_open_play, name="create_open_play"),
    path("add_product/", views.add_product, name="add_product"),
    path("product_list/", views.product_list, name="product_list"),
    path("view_product/<int:product_id>/", views.view_product, name="view_product"),
    path("edit_product/<int:product_id>/", views.edit_product, name="edit_product"),
    path("delete_product/<int:product_id>/", views.delete_product, name="delete_product"),
    
    path("send_universal_notification/", views.send_universal_notification, name="send_universal_notification"),
    path("payment_table/", views.payment_table, name="payment_table"),

    path("merchant_request_list/",views.merchant_request_list, name="merchant_request_list"),
    path("version_update_list/", views.version_update_list, name="version_update_list"),
    path("update_version/", views.version_update, name="update_version"),
    
    path("read_notification/", views.mark_notifications_as_read, name="mark_notifications_as_read"),


    #socail feed
    path("social_feed_list/", views.social_feed_list, name="social_feed_list"),
    path("add_social_feed/", views.add_social_feed, name="add_social_feed"),
    path("social_feed_view/<int:post_id>/", views.social_feed_view, name="social_feed_view"),
    path("edit_social_feed/<int:post_id>/", views.edit_social_feed, name="edit_social_feed"),
    path("delete_file/<int:file_id>/", views.delete_file, name="delete_file"),

    path('club_list/', views.club_list, name="club_list")
    
]

apps/chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('6a718e7164a587c105106342bb18ec50a034a0854ddc49f4ffb571eeb79199ea/', views.chat_user_details, name="chat_user_details"),
    path('10b52a019c8ba09bcb8d65340e34808b06b4211373d31e5ff6b2c6cb98100f81/', views.chat_list, name="chat_list"),
    path('a66ff4d19715790748d52bc90ffb9ab31a779c6ddaa07c5d29783f3f4683d43b/', views.chat_list_using_pagination, name="chat_list_using_pagination"),
    
    path("6626829e840eb07406be20c2501a77e733ea5b2bd77016e8217f6508c98962de/", views.user_chat_list, name="user_chat_list"),
    path("64743355d8fbeba657a087fc386bc2faef4a70f57ebc711eeb78c51a953f2a05/", views.chat_user_list, name="chat_user_list"),
    path('1eda0f0d25d5d2597ba503f24a94419d0a6108d24d3c4fcfb9559bb172e55316/', views.unread_chat_users, name="unread_chat_users"),
    path('cc450ba718d0c868196a7649ca2019976e1301435faaa476cee2feb11978b4d9/', views.block_or_unblock_chat_user, name="block_or_unblock_chat_user"),
    path('4d4cdd5a76f7a2e973d5abef6ba8b2a67fc4537243fb345dfdbdf677aa190a7c/', views.continue_chat_with_user, name="continue_chat_with_user"),
    path('dea9b1c83b207758a9f7895a36c9cd3e4ecbb7635d571b26f84ae2b2f3c3a20f/', views.report_chat_user, name="report_chat_user"),
    # path("<str:room_name>/", views.room, name="room"),
    # path("<str:natificatio_name>/", views.natificatio_name, name="natificatio_name"),

    path('df225338df37a2d169a8438f8a1d4837752f5ee278e01d42eb97ce349e59b7ff/', views.search_chat_user_by_name, name='search_chat_user_by_name'),
    path('98dbfe0c27e09f22fb8804841d774a05194ba5822ff938fe6b01e40dc2c48375/', views.create_chat_room, name='create_chat_room'),
    path('90b91c2d3d44924670acbb2485e4e54847eab86c14b94202bb5fc4a2e79f446b/', views.mark_msgs_as_read, name='mark_msgs_as_read'),
    path('ea7f409b7bec1b4d9c81f346a3aa4320dde219fd9b52287caa649259587c4366/', views.get_room_user_status, name='get_room_user_status'),


    path('get_user_search/', views.get_user_search, name="get_user_search"),

]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apps.user.views import account_deletion_request
from apps.team import views
from django.shortcuts import render
from apps.user.views import event_matches_table
from apps.user.models import User
from datetime import datetime
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def account_deletion_requestweb(request):
    context = {"message": None}
    try:
        if request.method == "POST":
        
            email = request.POST.get('email')
            reason = request.POST.get('reason', None)  # Get reason for deletion
            user_ins = User.objects.filter(email=email)
            
            if not user_ins.exists():
                context["message"] = "not find user"
                return render(request, 'email/deletion_request.html', context)
            user = user_ins.first()
            # Prepare email content
            context = {
                "full_name": f"{user.first_name} {user.last_name}",
                "user_email": email,
                "reason": reason,
                "date_now": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            }

            # Render HTML email
            html_content = render_to_string('email/delete_request.html', context)
            text_content = strip_tags(html_content)  # Plain text version

            # Send email
            subject = "Request for Account Deletion"
            from_email = email  # The user's email address
            # recipient_list = ["joinpickleit@gmail.com"]  # Admin email
            recipient_list = ["joinpickleit@gmail.com"]

            email_message = EmailMultiAlternatives(subject, text_content, from_email, recipient_list)
            email_message.attach_alternative(html_content, "text/html")
            email_message.send()

            return render(request, 'email/deletion_request.html', context)
        else:
            return render(request, 'email/deletion_request.html', context)
    except Exception as e:
        context["message"] = str(e)
        return render(request, 'email/deletion_request.html', context)

def index(req):
    return render(req, "index/index.html")

def privacy_policy(req):
    return render(req, "index/privacy-policy.html")

def terms_conditions(req):
    return render(req, "index/terms-conditions.html")

urlpatterns = [
    path('', index, name="index"),
    path('privacy_policy/', privacy_policy, name="privacy_policy"),
    path('terms_conditions/', terms_conditions, name="terms_conditions"),
    path('pickleit-admin-main/', admin.site.urls),
    path('api_list/', views.api_list,name="api_list"),
    path('user/', include('apps.user.urls')),
    path('team/', include('apps.team.urls')),
    path('accessories/', include('apps.pickleitcollection.urls')),
    path('chat/', include('apps.chat.urls')),
    path('admin/', include('apps.admin_side.urls')),
    path('accessories/', include('apps.store.urls')),
    path('court/', include('apps.courts.urls')),
    path('socialfeed/', include('apps.socialfeed.urls')),
    path('clubs/', include('apps.clubs.urls')),
    path('user_side/', include('apps.user_side.urls')),
    path('requestdeletion1/', account_deletion_request, name="account_deletion_request"),
    path('requestdeletion/', account_deletion_requestweb, name="account_deletion_requestweb"),
    path('events/matches/table/', event_matches_table, name="event_matches_table"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/admin_side/models.py
from django.db import models

# Create your models here.

apps/chat/models.py
from django.db import models
from apps.user.models import *

from apps.team.models import *
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.db.models.signals import post_save
from django.dispatch import receiver
from apps.user.helpers import send_push_notifications
# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=100)
    user_one = models.ForeignKey(User, on_delete=models.CASCADE,related_name="user_one")
    user_two = models.ForeignKey(User, on_delete=models.CASCADE,related_name="user_two")
    is_blocked_user_one = models.BooleanField(default=False)
    is_blocked_user_two = models.BooleanField(default=False)

    def __str__(self) :
        return f"{self.name}, {self.user_one.email}, {self.user_two.email}"
    

class MessageBox(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="room")
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="sender_user")
    reciver_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="reciver_user")
    is_read = models.BooleanField(default=False)
    text_message = models.TextField()
    send_file = models.FileField(upload_to="chat_file/", null=True, blank=True)
    send_image = models.FileField(upload_to="chat_image/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self) :
        return f"Room: {self.room.name}, Sender:{self.sender_user.email}, Reciver:{self.reciver_user.email}"



class NotifiRoom(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="room_user",null=True, blank=True)
    
    def __str__(self) :
        return f"{self.name}"   

class NotificationBox(models.Model):
    room = models.ForeignKey(NotifiRoom, on_delete=models.CASCADE, related_name="NotifiRoom", null=True, blank=True)
    titel = models.CharField(max_length=100)
    text_message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    notify_for = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notification_for",null=True, blank=True)
    is_universal = models.BooleanField(default=False)

    def __str__(self) :
        return f"{self.titel}:-{self.text_message}, Read-status{self.is_read}"

    def save(self, *args, **kwargs):
        is_new = self._state.adding
        super(NotificationBox, self).save(*args, **kwargs)
        # Send notification to WebSocket clients only if the instance is being updated, not when it's being created.
        self.send_notification()

    def send_notification(self):
        channel_layer = get_channel_layer()
        
        if self.is_universal:
            group_name = "universal_notifications"
        else:
            group_name = f"notifications_{self.room.name}"
        
        async_to_sync(channel_layer.group_send)(
            group_name,
            {
                "type": "send_notification",
                "notification": {
                    "id": self.id,
                    "title": self.titel,
                    "text_message": self.text_message,
                    "is_read": self.is_read,
                    "created_at": self.created_at.isoformat(),
                }
            }
        )


@receiver(post_save, sender=NotificationBox)
def send_push_notification_on_create(sender, instance, created, **kwargs):
    if created:
        user = instance.notify_for
        if user:
            check_token = FCMTokenStore.objects.filter(user=user)
            if check_token.exists():
                try:
                    token_list = check_token.first().fcm_token.get("fcm_token", [])
                    if token_list:
                        send_push_notifications(token_list[0], instance.titel, instance.text_message)
                except:
                    pass


apps/admin_side/templates/dashboard/authentication-login.html
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="dashboard/images/favicon.png">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
    <!-- Custom CSS -->
    <link href="dashboard/css/style.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center bg-dark">
            <div class="auth-box bg-dark border-top border-secondary">
                <div id="loginform1">
                    <div class="text-center p-t-20 p-b-20">
                        <span class="db"><img src="dashboard/images/logo.png" alt="logo" /></span>
                    </div>
                    <!-- Form -->
                    <form class="form-horizontal m-t-20" id="loginform" action="index.html">
                        <div class="row p-b-30">
                            <div class="col-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-success text-white" id="basic-addon1"><i class="ti-user"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" required="">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-warning text-white" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" required="">
                                </div>
                            </div>
                        </div>
                        <div class="row border-top border-secondary">
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="p-t-20">
                                        <button class="btn btn-info" id="to-recover" type="button"><i class="fa fa-lock m-r-5"></i> Lost password?</button>
                                        <button class="btn btn-success float-right" type="submit">Login</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div id="recoverform">
                    <div class="text-center">
                        <span class="text-white">Enter your e-mail address below and we will send you instructions how to recover a password.</span>
                    </div>
                    <div class="row m-t-20">
                        <!-- Form -->
                        <form class="col-12" action="index.html">
                            <!-- email -->
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger text-white" id="basic-addon1"><i class="ti-email"></i></span>
                                </div>
                                <input type="text" class="form-control form-control-lg" placeholder="Email Address" aria-label="Username" aria-describedby="basic-addon1">
                            </div>
                            <!-- pwd -->
                            <div class="row m-t-20 p-t-20 border-top border-secondary">
                                <div class="col-12">
                                    <a class="btn btn-success" href="#" id="to-login" name="action">Back To Login</a>
                                    <button class="btn btn-info float-right" type="button" name="action">Recover</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="dashboard/js/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="dashboard/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="dashboard/js/bootstrap.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>

    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    // ============================================================== 
    // Login and Recover Password 
    // ============================================================== 
    $('#to-recover').on("click", function() {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
    });
    $('#to-login').click(function(){
        
        $("#recoverform").hide();
        $("#loginform").fadeIn();
    });
    </script>

</body>

</html>

apps/admin_side/templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div class="page-breadcrumb">
            <div class="row p-2">
                <div class="col-12">
                    <h3 class="page-title font-weight-bold">Hi, {{request.user.username}}</h3>
                    <h6 > Welcome to your dashboard</h6>
                 
                    <div class="ml-auto text-right">
                        <nav aria-label="breadcrumb">
                            {% comment %} <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Library</li>
                            </ol> {% endcomment %}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="row p-4">
            <div class="col-md-6 col-lg-4 col-xlg-3">
                <div class="card card-hover">
                    <div class="box text-center" style="background: radial-gradient( circle farthest-corner at 92.3% 71.5%,  rgba(83,138,214,1) 0%, rgba(134,231,214,1) 90% );">
                        <div class="row justify-content-end p-3">
                            <h4 class="text-white"><a href="{% url 'dashboard:player_list_' %}" class="text-decoration-none text-dark">Total Players</a></h4>
                        </div>
                        <div class="row align-items-center">
                            <div class="col-6 " >
                                <h1 class="font-light text-white"><i class="mdi mdi-tennis" style="font-size:55px;"></i></h1>
                            </div>
                            <div class="col-6 " >
                                <h5 class="m-b-0 m-t-5 text-white"style="font-size:65px;">{{total_player_count}}</h5>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 col-xlg-3">
                <div class="card card-hover">
                    <div class="box text-center" style="background: linear-gradient(to right, rgb(136, 181, 221), rgb(145, 234, 228));">
                        <div class="row justify-content-end p-3">
                            <h4 class="text-white"><a href="{% url 'dashboard:team_list_for_admin' %}" class="text-decoration-none text-dark">Total Teams</a></h4>
                        </div>
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h1 class="font-light text-white"><i class="mdi mdi-account-multiple" style="font-size:55px;"></i></h1>
                            </div>
                            <div class="col-6">
                                <h5 class="m-b-0 m-t-5 text-white"style="font-size:65px;">{{total_team_count}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 col-xlg-3">
                <div class="card card-hover">
                    <div class="box text-center" style="background: radial-gradient( circle farthest-corner at 10% 20%,  rgba(97,186,255,1) 0%, rgba(166,239,253,1) 90.1% );">
                        <div class="row justify-content-end p-3">
                            <h4 class="text-white"><a href="{% url 'dashboard:tournamnet_list' filter_by="all" %}" class="text-decoration-none text-dark">Total Tournamnets</a></h4>
                            
                        </div>
                        <div class="row align-items-center">
                            <div class="col-6">
                                <h1 class="font-light text-white"><i class="mdi mdi-trophy-variant" style="font-size:55px;"></i></h1>
                            </div>
                            <div class="col-6">
                                <h5 class="m-b-0 m-t-5 text-white"style="font-size:65px;">{{total_tournament_count}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h4 style="margin-left:35px;">Log details</h4>
        <div class="container-fluid p-4">
            <div class="card">           
                <div class="card-body">                    
                    <table id="log-details" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th class="h5 font-weight-bold">LOG TYPE</th>
                            <th class="h5 font-weight-bold">ACTION</th>
                            <th class="h5 font-weight-bold">INSTANCE ID</th>
                            <th class="h5 font-weight-bold">ACTION BY</th>
                            <th class="h5 font-weight-bold">ACTION DATE AND TIME</th>                                
                        </tr>
                        </thead>
                        <tbody>
                            {% if entries %}
                            {% for entry in entries %}
                            <tr>
                                <td>{{entry.model_name}}</td>
                                <td>{{entry.action}}</td>
                                <td>{{entry.instance_id}}</td>
                                <td>{{entry.user}}</td>
                                <td>{{entry.timestamp}}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="5" style="text-align:center;">No Data Available.</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>                   
                </div>
            </div>
        </div> 
{% endblock content %} 
       